---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: weatherApp-deployment
  namespace: base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp-v1
        image: konijo/weatherapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          memory: "16Mi"  #App will by standard use 16MB RAM and 50MilliCPU (1/2 CPU)
          cpu: "50m"
        limits:
          memory: "128Mi" #Limited to a maximum of 128MB RAM and 1 CPU
          cpu: "100m"